SECTIONS = (
    "summary",
    "experience",
    "projects",
    "skills",
    "education",
    "certifications",
    "languages",
    "other",
)


HEADING_ALIASES = {
    "about": "summary",
    "about me": "summary",
    "career objective": "summary",
    "objective": "summary",
    "personal statement": "summary",
    "professional summary": "summary",
    "profile": "summary",
    "summary": "summary",
    "career history": "experience",
    "employment": "experience",
    "employment history": "experience",
    "experience": "experience",
    "professional background": "experience",
    "professional experience": "experience",
    "work experience": "experience",
    "work history": "experience",
    "key projects": "projects",
    "open source": "projects",
    "personal projects": "projects",
    "projects": "projects",
    "selected projects": "projects",
    "side projects": "projects",
    "competencies": "skills",
    "core competencies": "skills",
    "core skills": "skills",
    "skills": "skills",
    "technical expertise": "skills",
    "technical skills": "skills",
    "technologies": "skills",
    "tools & technologies": "skills",
    "academic background": "education",
    "academic qualifications": "education",
    "education": "education",
    "qualifications": "education",
    "awards": "certifications",
    "awards & certifications": "certifications",
    "certificates": "certifications",
    "certifications": "certifications",
    "licenses": "certifications",
    "language skills": "languages",
    "languages": "languages",
}
